### ISSUE TITLE
[remind] [minor] [util/__init__.py ADDONS] Global reload reactor mutex

### ISSUE THREAD

**Issue by gkistler** [Clam-/pyBurlyBot#33]
Add global 'currently reloading' mutex for when we're reloading modules for threads to acquire when calling module-provided functions from util.ADDONS.  Minor, just to prevent weirdness, I doubt anything bad will happen from key lookup in the event that a module thread does a getattr on ADDONS while it's being modified.

**Comment by Clam-** [comment]
Addon's now use an interface similar to the module access interface, in that the request for an addon is done through the bot (container) which then gets the value called within the reactor.
