### ISSUE TITLE
Incorrect fractional time calculation

### ISSUE THREAD

**Issue by mauzel** [Clam-/pyBurlyBot#41]
Steps to Reproduce:

 - Join IRC channel with an instance of pyBurlyBot running
 - Issue the following message to the channel:

```
.remind me in 1.5days remindmessage
```

Expected Response:

```
<pyBurlyBot> <user>: I will remind you about that in 1 day and 12 hours.
```

Actual Response:

```
<pyBurlyBot> <user>: I will remind you about that in 1 day and 6 hours.
```

Please fix

This is a critical, blocking bug

**Comment by Clam-** [comment]
For the curious, the issue was caused with parseDateTime not handling reference time passed to it correctly. It wasn't "converting" localtime() to gmtime() in a sense.

**Comment by Clam-** [comment]
This isn't actually fixed yet. Also timezones :(

**Comment by Clam-** [comment]
Hopefully fixed now...
