### ISSUE TITLE
[everything] Link formatting

### ISSUE THREAD

**Issue by Clam-** [Clam-/pyBurlyBot#49]
So, the way we present URLs is usually ```(http://something.com)```
We are lucky that mIRC is smart about what it considers part of a URL, but other things aren't as smart. Steam for example treats characters as part of the URL.

It appears Steam will follow "email" convention of enclosing URLs in chevrons ```<http://something.com>```. I think this was some old defined standard or "suggestion" somewhere but I don't remember where I read it.

What do?

**Comment by gkistler** [comment]
I know I initiated the ball rolling a bit on getting stuff steam-friendly, but should we even bother caring about Steam stuff with regards to modules?  I feel as though it would just be more generally cumbersome to have modules handle stuff like output-aware formatting, unless you were thinking something like an output filter for steam-related stuff (like formatting URL-ish things to something steam-ish)?

The thing is, Steam chat allows for way more characters than IRC, so we're probably safe just outputting IRC-length/formatted things.  For what it's worth the normal Steam client will also auto-hyperlink http://example

**Comment by Clam-** [comment]
The only thing of interest is links... other formatting doesn't really matter.
The main reason it's of interest is that I can see people using ".g" or ".wiki" on steam because lame interface takes too long to do things and quicker to just click on link.
The other reason it was of interest is that "presenting a link" in text form is a discussed thing, although the only resource I can find at the moment is http://www.ietf.org/rfc/rfc2396.txt Section E.
Module doesn't need to be aware in the slightest. This is just "what do for convention" so it's as friendly to use as possible. (I know even with mIRC it can get tripped up on normal parens)

**Comment by Clam-** [comment]
Should we maybe not encapsulate URLs at all? And just display them spaced from other text?

**Comment by gkistler** [comment]
Separating with a space is basically how oldbbm did it for most things.
Seems the most straightforward to me as it's the most likely to "just work"
in whatever interface we're relaying to.  Sounds good to me

**Comment by Clam-** [comment]
Yessss, one stylistic choice down, 100 to go.
Thanks amigo.

**Comment by gkistler** [comment]
Closing this, we decided on no encapsulation for URLs.  Most apps/interfaces that auto-hyperlink things will rely on the scheme being present (sometimes not), if we find a scenario where our URLs aren't clickable we'll revisit this.
