### ISSUE TITLE
[module] Butt module

### ISSUE THREAD

**Issue by ckx** [Clam-/pyBurlyBot#56]
Every now and then, bbm should send a message replacing random strings in a line with the word "butt". I think hyphenate.py might be useful for this, I know old bbm used it: http://nedbatchelder.com/code/modules/hyphenate.py

\<@bbm\> I want a butt steelix

**Comment by Clam-** [comment]
no.

**Comment by dguenther** [comment]
:+1: this is an important feature

**Comment by ckx** [comment]
<@bbm> "for one of his abilbutties he slams the butt down in front of you and you can see your reflection, it then starts to butt out the butt"

**Comment by gkistler** [comment]
Resolved in 1edbec850382f6f96143428dd0129094d33d3033
