### ISSUE TITLE
[core] Investigate if SIGTERM is correctly handled i.e. REBOOT

### ISSUE THREAD

**Issue by Clam-** [Clam-/pyBurlyBot#61]
Don't forget.

**Comment by Clam-** [comment]
Really need to look in to this...

**Comment by Clam-** [comment]
On system reboot it appears that the process is just getting killed or twisted isn't doing the same process as when KeyboardInterupt occurs.
I don't know if I put in any special handling for KeyboardInterupt, but it would be good if SIGTERM was handled the same way, since KeyboardInterupt closes the bot down cleanly.

**Comment by Clam-** [comment]
Alternatively maybe we get sqlite to do proper autocommiting or something.

**Comment by gkistler** [comment]
As pyburlybot is being run in a screen I suspect it might be receiving a SIGHUP or something along those lines if the SIGTERM hits the screen process first, but not 100% on that.  I'll look into it.

Also, if we're doing signal handling stuff we may as well throw in something like SIGUSR1 handling to reload file handles and/or reload whole bort.

If you have any thoughts on the extra stuff let me know.

**Comment by Clam-** [comment]
Oh huh, that's interesting. Didn't realise that Screen might be intercepting.
Special things for signal handling is kinda meh since OS things, but I think it would be nice to make sure it's at least bailing cleanly when requested.
I haven't tested bot on it's own without screen, so maybe we make a note somewhere if screen needs params to pass the signal on (if twisted handles it itself).

Thanks amigo.

**Comment by gkistler** [comment]
SIGINT / SIGTERM are getting handled and triggering the DB cleanup at least some of the time, and were definitely handled on the last restart which was noted to lose some DB data.  My current theory is that the shutdown doesn't always happen in a timely fashion and the bot gets SIGKILL'd before the DB commit finishes.

To confirm this we can add some additional debug output.  If my theory is correct the proper way to fix this will be to provide systemd/upstart/etc configuration to provide more shutdown time.
