### ISSUE TITLE
[Watch2Gether]

### ISSUE THREAD

**Issue by gkistler** [Clam-/pyBurlyBot#72]
Have BBM poll (or whatever) to grab the song title/youtube link to the deeplink moment at each second off of a watchtogether link.  On the reverse, allow the following to work well:

```
(10:39:49) <Grau> .yt butts
(10:39:49) <bbm> Butts (https://youtu.be/Qmkn59N5SDg), Why Do Guys Like Big Butts? (https://youtu.be/RociTssBCAg), Far Cry Primal Gameplay Walkthrough Part 2 - BUTTS ON FIRE!! (https://youtu.be/CjMBu5T-V-Y), BUTTS (https://youtu.be/spwMlAkGkao), Butts, Birds and Bars - It's SF Animated! (https://youtu.be/YruYx-C9tBk)
(10:40:12) <Grau> .watch2 [2]t=3m
```

**Comment by Clam-** [comment]
I know you really like watchtogether, but I don't really care much for it.
Feel free to write a thing for it though (this is me saying sry I don't want to do it.)
