### ISSUE TITLE
[random] Various additional functionality

### ISSUE THREAD

**Issue by gkistler** [Clam-/pyBurlyBot#75]
Implement the following features in the random module:

- Specify randint MIN/MAX (from oldbbm)

	**Input:** Integer
	**Output:** Random integer in the range `0` - `input`
	>    \<user> .rand 23691
	>    \<bot> 5634

- Random single character from a string (from oldbbm)

	**Input:** Single string that does not represent an `int`
	**Output:** Random single character from input
	>    \<user> .rand abdef
	>    \<bot> b

- Chance for a coin to land on its side (from oldbbm)
- Error when multiple choices are provided but only one output is possible

	>    \<user> .rand test test
	>    \<bot> I will not be party to this.

**Comment by Clam-** [comment]
coin toss is already there .heads .tails, etc.

Not sure how useful random character from a string would be, but not really any downside to it.
I thought rand should already do 0-INT, but maybe I forgot that. Good idea.

**Comment by Clam-** [comment]
Oh wait, by coin on it's side, do you mean troll output... lol that's silly, but I kinda like it.
